_schema: _schema
source: /
paths:
  uploads: public/uploads
  static: public
collections_config:
  src_pages_posts:
    path: src/pages/posts
    name: Src Pages Posts
    icon: sports_esports
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Asia/Shanghai
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
